#define MAINPREFIX ik
#define PREFIX unsci
#define PREFIX_BEAUTIFIED UNSC Infirmary

#include "script_version.hpp"
#define VERSION MAJOR.MINOR
#define VERSION_STR MAJOR.MINOR.PATCH.BUILD
#define VERSION_AR MAJOR,MINOR,PATCH.BUILD
#define REQUIRED_VERSION 2.20

#define AUTHOR QUOTE(Im Kreepy)

#ifndef COMPONENT_BEAUTIFIED
    #define COMPONENT_BEAUTIFIED COMPONENT
#endif
#ifdef SUBCOMPONENT_BEAUTIFIED
    #define COMPONENT_INFO PREFIX_BEAUTIFIED - COMPONENT_BEAUTIFIED - SUBCOMPONENT_BEAUTIFIED
#else
    #define COMPONENT_INFO PREFIX_BEAUTIFIED - COMPONENT_BEAUTIFIED
#endif
#define COMPONENT_NAME QUOTE(COMPONENT_INFO)
