[stringtables.usage]
options.ignore = [
    "str_ace_medical_damage_unsci_blamitewound",
    "str_ace_medical_damage_unsci_blamitewound_large",
    "str_ace_medical_damage_unsci_blamitewound_medium",
    "str_ace_medical_damage_unsci_blamitewound_minor",
    "str_ace_medical_damage_unsci_spikewound",
    "str_ace_medical_damage_unsci_spikewound_large",
    "str_ace_medical_damage_unsci_spikewound_medium",
    "str_ace_medical_damage_unsci_spikewound_minor",
    "str_ace_medical_damage_unsci_plasmaavulsion",
    "str_ace_medical_damage_unsci_plasmaavulsion_large",
    "str_ace_medical_damage_unsci_plasmaavulsion_medium",
    "str_ace_medical_damage_unsci_plasmaavulsion_minor",
    "str_ace_medical_damage_unsci_plasmaburn",
    "str_ace_medical_damage_unsci_plasmaburn_large",
    "str_ace_medical_damage_unsci_plasmaburn_medium",
    "str_ace_medical_damage_unsci_plasmaburn_minor",
]

[sqf.var_all_caps]
options.ignore = [
    "ACE_*",
]
